### ISSUE TITLE
Issue with IDN domains

### ISSUE THREAD

**Issue by infiniteloopltd** [webprofusion/certify#251]
When trying to register http://www.xn--c1aeudebqd.com/ ([госномер.com](http://госномер.com)) the registration failed with this in the error log:

2018-02-02 09:28:52.577 +00:00 [INF] Attempting Domain Validation: госномер.com
2018-02-02 09:28:52.578 +00:00 [INF] Registering and Validating госномер.com 
2018-02-02 09:28:55.096 +00:00 [INF] Performing Challenge Response via IIS: госномер.com 
2018-02-02 09:28:56.222 +00:00 [INF] Requesting Validation from Let's Encrypt: госномер.com
2018-02-02 09:28:58.227 +00:00 [INF] Domain validation completed: госномер.com
2018-02-02 09:28:58.229 +00:00 [INF] Requesting Certificate via Lets Encrypt
2018-02-02 09:29:06.998 +00:00 [INF] Completed Certificate Request.
2018-02-02 09:29:07.033 +00:00 [INF] Performing Automated Certificate Binding
2018-02-02 09:29:08.352 +00:00 [INF] regcheck.org.uk: Request failed - Decoded string is not a valid IDN name.
Parameter name: ascii System.ArgumentException: Decoded string is not a valid IDN name.
Parameter name: ascii
   at System.Globalization.IdnMapping.GetUnicodeUsingOS(String ascii)
   at System.Globalization.IdnMapping.GetUnicode(String ascii, Int32 index, Int32 count)
   at System.Globalization.IdnMapping.GetUnicode(String ascii, Int32 index)
   at Certify.Management.IISManager.ToUnicodeString(String input) in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 427
   at Certify.Management.IISManager.<InstallCertForRequest>d__31.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 463
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 717
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420
2018-02-02 09:29:08.353 +00:00 [INF] regcheck.org.uk: Request failed - Decoded string is not a valid IDN name.
Parameter name: ascii System.ArgumentException: Decoded string is not a valid IDN name.
Parameter name: ascii
   at System.Globalization.IdnMapping.GetUnicodeUsingOS(String ascii)
   at System.Globalization.IdnMapping.GetUnicode(String ascii, Int32 index, Int32 count)
   at System.Globalization.IdnMapping.GetUnicode(String ascii, Int32 index)
   at Certify.Management.IISManager.ToUnicodeString(String input) in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 427
   at Certify.Management.IISManager.<InstallCertForRequest>d__31.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 463
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 717
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420

**Comment by stefanbg** [comment]
I have the same problem but with Swedish character å 

According to this letsencrypt support IDN
https://community.letsencrypt.org/t/idn-support-enabled/21469

**Comment by webprofusion-chrisc** [comment]
Thanks, looks like we have a regression in idn support. This will resolved in the next release.

**Comment by Apoc70** [comment]
Any update on this issue? Build 3.0.11.30336 still encounters that error.

IIS requires that the website binding does not use the IDN notation, but the full domain name in local language only.

**Comment by glat** [comment]
This bug is present in latest 4.0.4 release. Please check it.
Thanks

**Comment by webprofusion-chrisc** [comment]
@glat thanks can you give an example domain please?
